### ISSUE TITLE
A few questions/comments

### ISSUE THREAD

**Issue by NoLooseEnds** [looselyrigorous/docker-rtorrent#1]
I'm pretty new to docker, so please bear with me. :)

**Attach/detach rtorrent?**
Is it possible to attach to the rtorrent interface inside the docker like it is now?

I have been experimenting with implementing tmux/screen, but I'm having issues with running `screen` "behind" `su-exec` (because of changing uid/gid). So I tried start screen as root, and then run `su-exec` with the custom uid inside the screen session.

```
exec screen -d -m -fa -S rtorrent su-exec $PUID:$PGID rtorrent -n -o import=/config/.rtorrent.rc
```

That sort of works, but I'm not getting the rtorrent interface. I'm only getting the logging output? Could that have anything to do with the docker linking `ln -sf /dev/stdout /var/log/rtorrent-info.log`?

How do you bring up the rtorrent interface? Or do you just use Flood?

**Restarting on crash?**
What happens if rtorrent crashes? Does docker detect this, and restarts the container? Or do I need to include a script that checks for this and restarts on crash?

**Using `RUN` instead of `&&`**
Also, apparently, it's a [better practice](https://itnext.io/3-simple-tricks-for-smaller-docker-images-f0d2bda17d1e) to use "RUN" multiple times, instead of "&&". :
```
RUN apk add --no-cache \
      rtorrent \
      su-exec
RUN    mkdir -p \
      /dist \
      /config \
      /session \
      /socket \
      /watch/load \
      /watch/start \
      /downloads
RUN   ln -sf /dev/stdout /var/log/rtorrent-info.log
RUN   ln -sf /dev/stderr /var/log/rtorrent-error.log
```

Thanks! :)

**Comment by looselyrigorous** [comment]
Hello!

**Attaching to the ncurses ui**
For me being able to use the ncurses rtorrent interface was out of scope to begin with, as other projects already accomplish [this](https://github.com/binhex/arch-rtorrentvpn). You should look at what other containers do to offer this functionality.

If you want to work off of this, you have to use `tmux`. You don't want to `docker attach`, like you would when using screen. That would attach to PID 1 whose output I've hijacked with the symlinks (this is why you were getting the log output in your attempts). Instead you would do something like `docker-compose exec rtorrent tmux attach`, which would launch a new tmux process that attaches to the session created when the container starts. You also need to remove the daemon mode setting in rtorrent.rc

**Restarting on crash**
I rely on `docker-compose` for this, using the [restart](https://docs.docker.com/compose/compose-file/#restart) option.

Also thanks for letting me know about the multiple RUN's merging thing!

**Comment by NoLooseEnds** [comment]
Thanks for the pointers. :) I like your setup, since it's so clean. 

I normally use Flood, but I also like to have access to the ncurses ui. I'll poke around in the link you provided and see if I get it up and running.
