### ISSUE TITLE
rtorrent: std::bad_alloc

### ISSUE THREAD

**Issue by Sparticuz** [looselyrigorous/docker-rtorrent#5]
Getting this error in my log with constant restarts since pulling latest. rTorrent not coming up. Tried with my config and tried with bootstrap'ed config. Any ideas?

**Comment by looselyrigorous** [comment]
Hmmm, I can not reproduce. I had ran the image like `docker run -it --rm docker-rtorrent` before pushing. I'd also tested the changes in my own instance and it worked fine. The only significant change was updating the base image to Alpine 3.10.

Have you checked if you're not running out of RAM?

**Comment by Sparticuz** [comment]
It looks like my problem is unrelated to this container. My hard drive is reading 95% full in df, but only 45% full in du. Something going on with my drive.

**Comment by Sparticuz** [comment]
Yep, I accidentally had some files hidden behind a mount point that made my drive look full.
